default_install_hook_types: [pre-push]

repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ["--"]
      - id: clippy
        args: ["--all-targets", "--all-features", "--", "-D", "warnings"]
